project:
  type: website
  output-dir: docs

website:
  title: "Lucas Okwudishu"
  site-url: "https://lucaso21.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
        
  page-footer:
    center: |
      <span class="container"><strong>Made with [Posit Quarto](https://quarto.org/){target="_blank"}</strong></span>
    background: "#2c3e50"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    
    
    



