project:
  type: website
  output-dir: docs

website:
  title: "Lucas Okwudishu"
  site-url: "https://lokwudishu.com"
  favicon: "Lucas Okwudishu"
  #site-url: "https://lucaso21.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: blog.qmd
        text: Blog
      
    right: 
      - icon: linkedin
      - href: https://linkedin.com/in/lucasokwudishu
      - aria-label: Quarto Linkedln
      - icon: github
      - href: https://github.com/LucasO21/
      - aria-label: Quarto Github
      - icon: medium
      - href: https://medium.com/@clfo2014
      - aria-label: Quarto Medium
  
        
  page-footer:
    center: |
      <span class="container"><strong>Made with [Posit Quarto](https://quarto.org/){target="_blank"}</strong></span>
    background: "#2c3e50"

format:
  html:
    includes:
      in-header: navbar-styles.css
    theme: flatly
    css: styles.css
    toc: true
    
    
    



