project:
  type: website
  output-dir: docs

website:
  title: "Lucas Okwudishu"
  site-url: "https://lucaso21.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



